[project]
name = "data"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "holidays>=0.56",
    "lxml>=6.1.2",
    "mapbox-vector-tile>=2.2.0",
    "numpy>=2.4.4",
    "openpyxl>=3.1.5",
    "pillow>=12.3.0",
    "requests>=2.33.1",
    "scipy>=1.17.1",
    "shapely>=2.1.2",
]
